create extension if not exists "uuid-ossp";
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,nome text,avatar_url text,role text not null default 'user' check(role in('user','admin')),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.albums(id uuid primary key default uuid_generate_v4(),nome text not null,descricao text,ano integer,capa_url text,total_stickers integer default 0,ativo boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.selections(id uuid primary key default uuid_generate_v4(),nome text not null,tipo text default 'selecao',logo_url text,created_at timestamptz default now());
create table if not exists public.sticker_types(id uuid primary key default uuid_generate_v4(),nome text not null,created_at timestamptz default now());
create table if not exists public.stickers(id uuid primary key default uuid_generate_v4(),album_id uuid not null references public.albums(id) on delete cascade,codigo text not null,nome text not null,selection_id uuid references public.selections(id) on delete set null,type_id uuid references public.sticker_types(id) on delete set null,foto_url text,ordem integer,created_at timestamptz default now(),updated_at timestamptz default now(),unique(album_id,codigo));
create table if not exists public.collections(id uuid primary key default uuid_generate_v4(),user_id uuid not null references public.profiles(id) on delete cascade,album_id uuid not null references public.albums(id) on delete cascade,created_at timestamptz default now(),unique(user_id,album_id));
create table if not exists public.user_stickers(id uuid primary key default uuid_generate_v4(),user_id uuid not null references public.profiles(id) on delete cascade,sticker_id uuid not null references public.stickers(id) on delete cascade,quantidade integer not null default 0 check(quantidade>=0),updated_at timestamptz default now(),unique(user_id,sticker_id));
alter table public.profiles enable row level security; alter table public.albums enable row level security; alter table public.selections enable row level security; alter table public.sticker_types enable row level security; alter table public.stickers enable row level security; alter table public.collections enable row level security; alter table public.user_stickers enable row level security;
create policy "profiles own select" on public.profiles for select to authenticated using(id=auth.uid());
create policy "profiles own update" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "albums active select" on public.albums for select to authenticated using(ativo=true);
create policy "selections select" on public.selections for select to authenticated using(true);
create policy "types select" on public.sticker_types for select to authenticated using(true);
create policy "stickers select" on public.stickers for select to authenticated using(true);
create policy "collections own select" on public.collections for select to authenticated using(user_id=auth.uid());
create policy "collections own insert" on public.collections for insert to authenticated with check(user_id=auth.uid());
create policy "collections own delete" on public.collections for delete to authenticated using(user_id=auth.uid());
create policy "user stickers own select" on public.user_stickers for select to authenticated using(user_id=auth.uid());
create policy "user stickers own insert" on public.user_stickers for insert to authenticated with check(user_id=auth.uid());
create policy "user stickers own update" on public.user_stickers for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "user stickers own delete" on public.user_stickers for delete to authenticated using(user_id=auth.uid());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,nome,avatar_url) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name',split_part(coalesce(new.email,''),'@',1)),new.raw_user_meta_data->>'avatar_url') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
